# Options for compiling EMMA programs for SGI (IRIX 4.0.x).
# Distribution version.

RANLIB      = true
MEX_EXT     = mexsg
CMEX_LIBS   = -lemma -lminc_G0 -lnetcdf_G0 \
              -lsun -lm_G0 -lc_G0 \
              -lmalloc_G0
XDR_LIB     = -lsun
CC          = cc

# Options for the MIPS C compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CMEX_OPT    = -O2 -D__STDC__ -prototypes -G 0
STD_OPT     = -O2 -D__STDC__ -prototypes
