# Options for compiling EMMA programs for Linux
# Distribution version.

RANLIB      = 
MEX_EXT     = mexglx
CMEX_LIBS   = -lemma -lminc -lnetcdf -lm -lc
XDR_LIB     = 
CC          = cc

# Options for GCC compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -O3 -m486
CFLAGS_STD  = -O3 -m486
