# Options for compiling EMMA programs for Linux
# Distribution version.

RANLIB      = true
MEX_EXT     = mexlx
CMEX_LIBS   = -lemma -lminc -lnetcdf -lm -lc
XDR_LIB     = 
CC          = cc

# Options for GCC compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CMEX_OPT    = -O3 -m486
STD_OPT     = -O3 -m486
