#
# Makefile macros needed to put together an EMMA distribution.
#
# $Id: Makefile.version,v 1.6 2008-01-11 01:58:29 claude Exp $
#

# version number, release directory, and release archive file
PACKAGE = emma
VERSION = 0.9.9
RELEASE = $(PACKAGE)-$(VERSION)
ARCHIVE = $(RELEASE).tar.gz

# RCS stuff -- don't forget to change VERSION_SYM with VERSION!
VERSION_SYM = 0_9_9
NAME_SYM = $(PACKAGE)_v$(VERSION_SYM)
STATE = Rel
