# 
# Options for SGI (IRIX 5).
# 
# Development version - not to be included in EMMA distributions.
#
# $Id: Makefile.develop,v 1.3 2000-03-30 19:33:23 greg Exp $
#

RANLIB      = 
MEX_EXT     = mexsg
CMEX_LIBS   = -lemma -lminc -lnetcdf -lm
XDR_LIB     = 
CC          = cc

# Options for the MIPS C compiler.  CMEX_OPT is for CMEX programs,
# STD_OPT is for standalone programs.

CFLAGS_MEX  = -g -prototypes -fullwarn
CFLAGS_STD  = -g -prototypes -fullwarn
